
export var := D.T.Software
new := TDelphi

test : var := test-var
%e : override new := test-new

test : anoher
	@echo "test :"
	@echo "var => $(var)"
	@echo "new => $(new)"

anoher	:
	@echo "another  :"
	@echo "var => $(var)"
	@echo "new => $(new)"

rule :
	@echo "rule :"
	@echo "var => $(var)"
	@echo "new => $(new)"
